//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPresenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPresenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\VideoLibrary\Images\.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\.
        /// </summary>
        public static string LibraryPath {
            get {
                return ResourceManager.GetString("LibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\VideoLibrary\Loops\.
        /// </summary>
        public static string LoopPath {
            get {
                return ResourceManager.GetString("LoopPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\AudioLibrary\Music\.
        /// </summary>
        public static string MusicPath {
            get {
                return ResourceManager.GetString("MusicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\AudioLibrary\Pads\.
        /// </summary>
        public static string PadPath {
            get {
                return ResourceManager.GetString("PadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\VideoLibrary\Images\LivingRoomTitle.jpg.
        /// </summary>
        public static string PlaceholderImagePath {
            get {
                return ResourceManager.GetString("PlaceholderImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\service.xml.
        /// </summary>
        public static string SettingsFilePath {
            get {
                return ResourceManager.GetString("SettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\SongLibrary\.
        /// </summary>
        public static string SongPath {
            get {
                return ResourceManager.GetString("SongPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file://127.0.0.1/c$/Users/Owner/Desktop/MyPresenterLibrary/SpotifyEmbed.htm.
        /// </summary>
        public static string SpotifyPath {
            get {
                return ResourceManager.GetString("SpotifyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Owner\Desktop\MyPresenterLibrary\VideoLibrary\Videos\.
        /// </summary>
        public static string VideoPath {
            get {
                return ResourceManager.GetString("VideoPath", resourceCulture);
            }
        }
    }
}
